<a href="https://colab.research.google.com/github/AdityaMohanty374/ML_Algos/blob/main/SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [41]:
import pandas as pd
import numpy as np
df = pd.read_csv('cars_dataset.csv')

In [36]:
df['buying'] = df['buying'].replace({
    'vhigh':3,
    'high':2,
    'med':1,
    'low':0
})
df['maint'] = df['maint'].replace({
    'vhigh':9,
    'high':8,
    'med':7,
    'low':6
})
df['doors'] = df['doors'].replace({
    '5more':15,
    'five':14,
    'four':13,
    'three':12,
    'two':11
})
df['persons'] = df['persons'].replace({
    'more':19,
    'four':18,
    'two':17
})
df['lug_boot'] = df['lug_boot'].replace({
    'big':23,
    'med':22,
    'small':21
})
df['safety'] = df['safety'].replace({
    'high':32,
    'med':31,
    'low':30
})
df['car'] = df['car'].replace({
    'unacc':50,
    'acc':51,
    'good':52,
    'vgood':53
})
df

/tmp/ipython-input-916063931.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['buying'] = df['buying'].replace({
/tmp/ipython-input-916063931.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['maint'] = df['maint'].replace({
/tmp/ipython-input-916063931.py:13: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasti

buying  maint  doors  persons  lug_boot  safety  car
0          3      9     11       17        21      30   50
1          3      9     11       17        21      31   50
2          3      9     11       17        21      32   50
3          3      9     11       17        22      30   50
4          3      9     11       17        22      31   50
...      ...    ...    ...      ...       ...     ...  ...
1723       0      6     15       19        22      31   52
1724       0      6     15       19        22      32   53
1725       0      6     15       19        23      30   50
1726       0      6     15       19        23      31   52
1727       0      6     15       19        23      32   53

[1728 rows x 7 columns]

In [40]:
#or this for data cleaning
df = df.replace({
    'buying': {
        'vhigh': 3,
        'high': 2,
        'med': 1,
        'low': 0
    },
    'maint': {
        'vhigh': 9,
        'high': 8,
        'med': 7,
        'low': 6
    },
    'doors': {
        '5more': 15,
        'five': 14,
        'four': 13,
        'three': 12,
        'two': 11
    },
    'persons': {
        'more': 19,
        'four': 18,
        'two': 17
    },
    'lug_boot': {
        'big': 23,
        'med': 22,
        'small': 21
    },
    'safety': {
        'high': 32,
        'med': 31,
        'low': 30
    },
    'car': {
        'unacc': 50,
        'acc': 51,
        'good': 52,
        'vgood': 53
    }
})
df

buying  maint  doors  persons  lug_boot  safety  car
0          3      9     11       17        21      30   50
1          3      9     11       17        21      31   50
2          3      9     11       17        21      32   50
3          3      9     11       17        22      30   50
4          3      9     11       17        22      31   50
...      ...    ...    ...      ...       ...     ...  ...
1723       0      6     15       19        22      31   52
1724       0      6     15       19        22      32   53
1725       0      6     15       19        23      30   50
1726       0      6     15       19        23      31   52
1727       0      6     15       19        23      32   53

[1728 rows x 7 columns]

In [43]:
# Auto-generate mapping dictionary, more faster
value_mapping_auto = {}
start_value = 1  # starting numeric code

for col in df.columns:
    unique_vals = df[col].unique()
    mapping = {val: code for code, val in enumerate(unique_vals, start=start_value)}
    value_mapping_auto[col] = mapping
    start_value += len(unique_vals)  # shift start so codes don't overlap across columns

print(value_mapping_auto)

{'buying': {'vhigh': 1, 'high': 2, 'med': 3, 'low': 4}, 'maint': {'vhigh': 5, 'high': 6, 'med': 7, 'low': 8}, 'doors': {'two': 9, 'three': 10, 'four': 11, '5more': 12}, 'persons': {'two': 13, 'four': 14, 'more': 15}, 'lug_boot': {'small': 16, 'med': 17, 'big': 18}, 'safety': {'low': 19, 'med': 20, 'high': 21}, 'car': {'unacc': 22, 'acc': 23, 'vgood': 24, 'good': 25}}


In [44]:
df = df.replace(value_mapping_auto)

/tmp/ipython-input-2299011084.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace(value_mapping_auto)


In [45]:
df

buying  maint  doors  persons  lug_boot  safety  car
0          1      5      9       13        16      19   22
1          1      5      9       13        16      20   22
2          1      5      9       13        16      21   22
3          1      5      9       13        17      19   22
4          1      5      9       13        17      20   22
...      ...    ...    ...      ...       ...     ...  ...
1723       4      8     12       15        17      20   25
1724       4      8     12       15        17      21   24
1725       4      8     12       15        18      19   22
1726       4      8     12       15        18      20   25
1727       4      8     12       15        18      21   24

[1728 rows x 7 columns]

In [50]:
X = df.drop(columns = 'car').values
y = df['car'].values

In [53]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,y,
    test_size = 0.2,
    random_state=42,
    stratify = y
)

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Import the Dataset
Dataset = pd.read_csv("cars_dataset.csv")
X = Dataset.iloc[:,:-1].values
y = Dataset.iloc[:, -1].values


#list all the string value and convert them in to int values!!
#Note we are doing only labelencoder
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
X[:, 0] = labelencoder.fit_transform(X[:, 0])
X[:, 1] = labelencoder.fit_transform(X[:, 1])
X[:, 2] = labelencoder.fit_transform(X[:, 2])
X[:, 3] = labelencoder.fit_transform(X[:, 3])
X[:, 4] = labelencoder.fit_transform(X[:, 4])
X[:, 5] = labelencoder.fit_transform(X[:, 5])


#Feature scaling the independent variable
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X = sc_X.fit_transform(X)

#Splitting the data into train and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)

#SVM Classification model
from sklearn.svm import SVC
classifier = SVC(C = 10.0, kernel = "linear",decision_function_shape='ovr')
classifier.fit(X_train, y_train)

#Predicting the output for our SGD Linear Model with the test set
y_pred = classifier.predict(X_test)

#evaluating our model.
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score
acc_train = accuracy_score(y_train, classifier.predict(X_train))
f1_train = f1_score(y_train, classifier.predict(X_train), average= 'weighted')

print("Traing set results")
print("ACCURACY for train set",acc_train)
print("F1 SCORE for train set",f1_train)

#evaluate our test set
acc_test = accuracy_score(y_test, y_pred)
f1_test = f1_score(y_test, y_pred, average= 'weighted')

print("Test set results")
print("ACCURACY for test set",acc_test)
print("F1 SCORE for test set",f1_test)

#Confusion Matrix
cm = confusion_matrix(y_test,y_pred)
print(cm)

Traing set results
ACCURACY for train set 0.7361455748552522
F1 SCORE for train set 0.6622604642278613
Test set results
ACCURACY for test set 0.7167630057803468
F1 SCORE for test set 0.6341355089951095
[[ 17   0 102   0]
 [  1   0  17   0]
 [  5   0 355   0]
 [ 12   0  10   0]]


In [3]:
X[:,0]

array([ 1.34164079,  1.34164079,  1.34164079, ..., -0.4472136 ,
       -0.4472136 , -0.4472136 ])